### PR TITLE
i18n implementation

### PR DESCRIPTION
**Pull request by alvarosamudio**
in order to internationalize the use of the plugin I added some lines to the cmake file that automate the creation of the translations, the plugin was translated to English and Spanish, also I added a file called build.sh that compiles and installs the plugin in the dde-dock automatically.

### CODE REVIEW

**Comment by alvarosamudio** [comment]
in order to internationalize the use of the plugin I added some lines to the cmake file that automate the creation of the translations, the plugin was translated to English and Spanish, also I added a file called build.sh that compiles and installs the plugin in the dde-dock automatically.

**Comment by xmuli** [comment]
These files will really be great, thank you very much, later I will improve its support for multi-language function, when the translation may need to be updated (PS: I with the original plan is also want to be lazy) 

image

**Review by xmuli — APPROVED** [review]
Great  PR

**Comment by alvarosamudio** [comment]
glad to have helped with the translations :D

**Pull request merged**
